services:
  db:
    image: postgres:16
    container_name: autisense_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: autisense
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: autisense_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@autisense.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  db_data: